-- Projetos / portfólio da Mafedo
CREATE TABLE projects (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(180) NOT NULL,
    slug VARCHAR(200) NOT NULL,
    short_description VARCHAR(320) NULL,
    description LONGTEXT NULL,
    main_image VARCHAR(255) NULL,
    category VARCHAR(120) NULL,
    location VARCHAR(160) NULL,
    year VARCHAR(9) NULL,
    client VARCHAR(160) NULL,
    segment VARCHAR(120) NULL,
    characteristics LONGTEXT NULL,
    featured TINYINT NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    seo_title VARCHAR(180) NULL,
    seo_description VARCHAR(320) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_projects_slug (slug),
    KEY idx_projects_status (status),
    KEY idx_projects_featured (featured),
    KEY idx_projects_category (category),
    KEY idx_projects_sort (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
